Api::V1::Greeting.create(greeting: 'Hello')
Api::V1::Greeting.create(greeting: 'Hola')
Api::V1::Greeting.create(greeting: 'Maakye')
Api::V1::Greeting.create(greeting: 'Bonjour')
Api::V1::Greeting.create(greeting: 'Howdy!')